### ISSUE TITLE
Article Table Template Not Found 

### ISSUE THREAD

**Issue by jennherrarte** [huantt/article-listing#1]
Hello! 

I'm getting the following error after registering my GitHub action and running the cron job using 
`{{ template "article-table" .Articles }}` : 

**Error**
`time=2023-09-15T05:14:45.684Z level=ERROR msg="html/template:article:4:12: no such template \"article-table\""`

No errors when using the listing template. 
<img width="1200" alt="Screenshot 2023-09-14 at 10 21 14 PM" src="https://github.com/huantt/article-listing/assets/36706323/1b992bb5-bc3a-4b02-931a-d288fd0459ec">

**Comment by huantt** [comment]
> Hello!
> 
> I'm getting the following error after registering my GitHub action and running the cron job using `{{ template "article-table" .Articles }}` :
> 
> **Error** `time=2023-09-15T05:14:45.684Z level=ERROR msg="html/template:article:4:12: no such template \"article-table\""`
> 
> No errors when using the listing template. <img alt="Screenshot 2023-09-14 at 10 21 14 PM" width="1200" src="https://user-images.githubusercontent.com/36706323/268181757-1b992bb5-bc3a-4b02-931a-d288fd0459ec.png">

Please try using the verison 1.1.0

**Comment by jennherrarte** [comment]
> > Hello!
> > I'm getting the following error after registering my GitHub action and running the cron job using `{{ template "article-table" .Articles }}` :
> > **Error** `time=2023-09-15T05:14:45.684Z level=ERROR msg="html/template:article:4:12: no such template \"article-table\""`
> > No errors when using the listing template. <img alt="Screenshot 2023-09-14 at 10 21 14 PM" width="1200" src="https://user-images.githubusercontent.com/36706323/268181757-1b992bb5-bc3a-4b02-931a-d288fd0459ec.png">
> 
> Please try using the verison 1.1.0

Ah I think the versions in this[ link](https://github.com/marketplace/actions/article-updater?version=v1.2.0) might point to the incorrect version in the .yml file. Would the cron job work the same to just alter this to the 1.1.0 version?  `uses: huantt/article-listing@v1.0.0`

Thanks!

**Comment by huantt** [comment]
> > > Hello!
> > > I'm getting the following error after registering my GitHub action and running the cron job using `{{ template "article-table" .Articles }}` :
> > > **Error** `time=2023-09-15T05:14:45.684Z level=ERROR msg="html/template:article:4:12: no such template \"article-table\""`
> > > No errors when using the listing template. <img alt="Screenshot 2023-09-14 at 10 21 14 PM" width="1200" src="https://user-images.githubusercontent.com/36706323/268181757-1b992bb5-bc3a-4b02-931a-d288fd0459ec.png">
> > 
> > 
> > Please try using the verison 1.1.0
> 
> Ah I think the versions in this[ link](https://github.com/marketplace/actions/article-updater?version=v1.2.0) might point to the incorrect version in the .yml file. Would the cron job work the same to just alter this to the 1.1.0 version? `uses: huantt/article-listing@v1.0.0`
> 
> Thanks!

I updated the version to follow Sematec versioning. In this case, my problem may be in the document, where I wrote the article-table in version 1.1.0 and above, but the version in the docs is still 1.0.0.
Please try using v1.1.0 and above to use the `article-table` feature

**Comment by jennherrarte** [comment]
Got it, thanks Jack!

**Comment by huantt** [comment]
@jennherrarte btw, I found another problem.
Please update the `run` state to:
```
          if git diff --exit-code; then
            echo "No changes to commit."
            exit 0
          else
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add .
            git commit -m "update"
            git push origin main
          fi
```

It helps you prevent errors when nothing has changed.

**Comment by jennherrarte** [comment]
> @jennherrarte btw, I found another problem. Please update the `run` state to:
> 
> ```
>           if git diff --exit-code; then
>             echo "No changes to commit."
>             exit 0
>           else
>             git config user.name github-actions
>             git config user.email github-actions@github.com
>             git add .
>             git commit -m "update"
>             git push origin main
>           fi
> ```
> 
> It helps you prevent errors when nothing has changed.

excellent, will do, thank you! @huantt
